PROC=hexagon
O1=loader
O2=elf_proc_def

include ../module.mak

# MAKEDEP dependency list ------------------
$(F)ana$(O) : $(I)auto.hpp $(I)bitrange.hpp $(I)bytes.hpp               \
	          $(I)config.hpp $(I)fpro.h $(I)funcs.hpp $(I)ida.hpp       \
	          $(I)idp.hpp $(I)kernwin.hpp $(I)lines.hpp $(I)llong.hpp   \
	          $(I)loader.hpp $(I)nalt.hpp $(I)name.hpp $(I)netnode.hpp  \
	          $(I)offset.hpp $(I)pro.h $(I)problems.hpp $(I)range.hpp   \
	          $(I)segment.hpp $(I)segregs.hpp $(I)typeinf.hpp           \
	          $(I)ua.hpp $(I)xref.hpp ../idaidp.hpp ana.cpp common.h
$(F)emu$(O) : $(I)auto.hpp $(I)bitrange.hpp $(I)bytes.hpp               \
	          $(I)config.hpp $(I)fpro.h $(I)frame.hpp $(I)funcs.hpp     \
	          $(I)ida.hpp $(I)idp.hpp $(I)kernwin.hpp $(I)lines.hpp     \
	          $(I)llong.hpp $(I)loader.hpp $(I)nalt.hpp $(I)name.hpp    \
	          $(I)netnode.hpp $(I)offset.hpp $(I)pro.h                  \
	          $(I)problems.hpp $(I)range.hpp $(I)segment.hpp            \
	          $(I)segregs.hpp $(I)struct.hpp $(I)typeinf.hpp            \
	          $(I)ua.hpp $(I)xref.hpp ../idaidp.hpp emu.cpp common.h
$(F)ins$(O) : $(I)auto.hpp $(I)bitrange.hpp $(I)bytes.hpp               \
	          $(I)config.hpp $(I)fpro.h $(I)funcs.hpp $(I)ida.hpp       \
	          $(I)idp.hpp $(I)kernwin.hpp $(I)lines.hpp $(I)llong.hpp   \
	          $(I)loader.hpp $(I)nalt.hpp $(I)name.hpp $(I)netnode.hpp  \
	          $(I)offset.hpp $(I)pro.h $(I)problems.hpp $(I)range.hpp   \
	          $(I)segment.hpp $(I)segregs.hpp $(I)typeinf.hpp           \
	          $(I)ua.hpp $(I)xref.hpp ../idaidp.hpp ins.cpp common.h
$(F)out$(O) : $(I)auto.hpp $(I)bitrange.hpp $(I)bytes.hpp               \
	          $(I)config.hpp $(I)fpro.h $(I)funcs.hpp $(I)ida.hpp       \
	          $(I)idp.hpp $(I)kernwin.hpp $(I)lines.hpp $(I)llong.hpp   \
	          $(I)loader.hpp $(I)nalt.hpp $(I)name.hpp $(I)netnode.hpp  \
	          $(I)offset.hpp $(I)pro.h $(I)problems.hpp $(I)range.hpp   \
	          $(I)segment.hpp $(I)segregs.hpp $(I)typeinf.hpp           \
	          $(I)ua.hpp $(I)xref.hpp ../idaidp.hpp common.h out.cpp
$(F)reg$(O) : $(I)auto.hpp $(I)bitrange.hpp $(I)bytes.hpp               \
	          $(I)config.hpp $(I)diskio.hpp $(I)fixup.hpp $(I)fpro.h    \
	          $(I)funcs.hpp $(I)ida.hpp $(I)idp.hpp $(I)ieee.h          \
	          $(I)kernwin.hpp $(I)lines.hpp $(I)llong.hpp               \
	          $(I)loader.hpp $(I)nalt.hpp $(I)name.hpp $(I)netnode.hpp  \
	          $(I)offset.hpp $(I)pro.h $(I)problems.hpp $(I)range.hpp   \
	          $(I)segment.hpp $(I)segregs.hpp $(I)typeinf.hpp           \
	          $(I)ua.hpp $(I)xref.hpp ../idaidp.hpp common.h reg.cpp
$(F)loader$(O) : $(I)auto.hpp $(I)bitrange.hpp $(I)bytes.hpp               \
	          $(I)config.hpp $(I)diskio.hpp $(I)fixup.hpp $(I)fpro.h    \
	          $(I)funcs.hpp $(I)ida.hpp $(I)idp.hpp $(I)ieee.h          \
	          $(I)kernwin.hpp $(I)lines.hpp $(I)llong.hpp               \
	          $(I)loader.hpp $(I)nalt.hpp $(I)name.hpp $(I)netnode.hpp  \
	          $(I)offset.hpp $(I)pro.h $(I)problems.hpp $(I)range.hpp   \
	          $(I)segment.hpp $(I)segregs.hpp $(I)typeinf.hpp           \
	          $(I)ua.hpp $(I)xref.hpp ../idaidp.hpp common.h loader.cpp
$(F)elf_proc_def$(O) : $(I)auto.hpp $(I)bitrange.hpp $(I)bytes.hpp               \
	          $(I)config.hpp $(I)diskio.hpp $(I)fixup.hpp $(I)fpro.h    \
	          $(I)funcs.hpp $(I)ida.hpp $(I)idp.hpp $(I)ieee.h          \
	          $(I)kernwin.hpp $(I)lines.hpp $(I)llong.hpp               \
	          $(I)loader.hpp $(I)nalt.hpp $(I)name.hpp $(I)netnode.hpp  \
	          $(I)offset.hpp $(I)pro.h $(I)problems.hpp $(I)range.hpp   \
	          $(I)segment.hpp $(I)segregs.hpp $(I)typeinf.hpp           \
	          $(I)ua.hpp $(I)xref.hpp ../idaidp.hpp common.h elf_proc_def.cpp
